application: ukropol 
version: 2
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+ 
  script: handle_incoming_email.py 
  login: admin

- url: /resources
  static_dir: resources

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: main.py
